---@meta

---@class ThreeCard : Game
---
---@field __super? Game
---
---@field game_state ThreeCardGameState
---
---@field constructor fun(self: self): nil
---
---[[ Game Loop ]]
---@field tick fun(self: self): nil
---
---[[ Game State Functions ]]
---@field deal fun(self: self): nil
---@field flipDealer fun(self: self): nil
---@field cleanup fun(self: self): nil
---
---[[ Event Handlers ]]
---@field onHandUILoaded fun(self: self, position: GameHandPosition): nil
---@field onObjectEnterZone fun(self: self, zone: Object, object: Object): nil
---@field onObjectLeaveZone fun(self: self, zone: Object, object: Object): nil
---@field onLeftButtonClick fun(self: self, player_color: string, color: string): nil
---@field onRightButtonClick fun(self: self, player_color: string, color: string): nil
---@field onCenterButtonClick fun(self: self, player_color: string, color: string): nil
